[package]
name = "debugc"
version = "0.1.0"
edition = "2021"

[dependencies]
hanoi = { path = "../lang" }
json-spanned-value = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"


