[package]
name = "debugger"
version = "0.1.0"
edition = "2024"

[dependencies]
hanoi = { path = "../lang" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dap = "0.4.1-alpha1"
anyhow = "1.0"
itertools = "0.14.0"
